# Generated by Django 2.1.5 on 2019-11-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='useId',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
