# Generated by Django 2.1.4 on 2019-11-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetcher', '0002_auto_20191106_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentMail',
            fields=[
                ('mailId', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
