# Generated by Django 2.1.4 on 2019-11-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetcher', '0003_contentmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmail',
            name='mailId',
            field=models.IntegerField(db_column='FId', primary_key=True, serialize=False),
        ),
    ]
