# Generated by Django 2.1.4 on 2019-11-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetcher', '0004_auto_20191107_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmail',
            name='mailId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
