# Generated by Django 2.1.4 on 2019-11-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetcher', '0005_auto_20191107_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmail',
            name='content',
            field=models.TextField(default='n'),
        ),
        migrations.AlterField(
            model_name='contentmail',
            name='name',
            field=models.TextField(default='n'),
        ),
    ]
