# Generated by Django 2.1.4 on 2019-11-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetcher', '0006_auto_20191107_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmail',
            name='mailId',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
