# Generated by Django 2.1.7 on 2019-11-08 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('efetcher', '0007_auto_20191107_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmail',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
