# Generated by Django 2.1.7 on 2019-11-08 06:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('efetcher', '0008_contentmail_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmail',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 6, 49, 18, 856705, tzinfo=utc)),
        ),
    ]
