# Generated by Django 2.1.7 on 2019-11-19 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('efetcher', '0010_auto_20191108_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmail',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 19, 10, 4, 49, 31264, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contentmail',
            name='mailId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
